name: grainos auto build

on:
  push:
    branches:
      - main  # main main main main main main main main

jobs:
  build:
    runs-on: ubuntu-latest # ubuntu is powering the github action lol L

    steps:
    - name: âœ… Checkout
      uses: actions/checkout@v2

    #- name: ðŸ› ï¸ Prepare environment
      #uses: RangHo/setup-arch@v1.1.0
      #with:
        #mirror: https://geo.mirror.pkgbuild.com
        #packages: "arch-install-scripts archiso awk dosfstools e2fsprogs erofs-utils findutils grub gzip libarchive libisoburn mtools openssl pacman sed squashfs-tools shellcheck python-docutils"

    - name: ðŸ’¿ Build archiso
      run: | 
        mkdir out
        echo $RANDOM > out/test.iso
      #shell: arch.sh {0}
      
    - name: ðŸŽ‰ Upload release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        files: |
          out/*.iso
